/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package media.server.GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import media.server.MediaServer;
import media.server.global.Instances;
import media.server.interfaces.LoadingInstanceListener;

/**
 *
 * @author ghpm9
 */
public class LoadingPanel extends javax.swing.JPanel implements LoadingInstanceListener {

    private Image background;
    private int value = 0;

    /**
     * Creates new form LoadingPanel
     */
    public LoadingPanel() {
        init();
    }

    private void init() {        
        loadBackGround();
        initComponents();       

        Thread thread = new Thread(() -> {
            addLoadingListener();
            Instances.init();
        });
        thread.start();
    }

    private void loadBackGround() {
        URL file = LoadingPanel.class.getResource("images/loading.gif");
        System.out.println(file.getFile());
        
        background = new ImageIcon(file).getImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        loadingBar.setBorderPainted(false);
        add(loadingBar, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo");
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawImage(background, 0, 0, getWidth(), getHeight(), this);
    }

    public void setValueProgress(int progress) {
        loadingBar.setValue(progress);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loadingBar;
    // End of variables declaration//GEN-END:variables

    private void addLoadingListener() {
        Instances.addListener(this);
    }

    @Override
    public void notify(String msg) {
        System.out.println(msg);
        value += 40;
        setValueProgress(value);
    }

    @Override
    public void completed() {
        System.out.println("Completo");
        setValueProgress(100);
        Instances.getIdlePanel().startThread();
        MediaServer.getMainFrameInstance().setPanel(Instances.getIdlePanel(), BorderLayout.CENTER, MainFrame.STATUS.IDLE);
    }
}
